"""empty message

Revision ID: 655161537604
Revises: 93885bf7c13f
Create Date: 2019-08-23 16:40:22.944193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655161537604'
down_revision = '93885bf7c13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
