"""empty message

Revision ID: 93885bf7c13f
Revises: 0561b35c6cc8
Create Date: 2019-08-23 15:40:06.273789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93885bf7c13f'
down_revision = '0561b35c6cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admission', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'admission')
    # ### end Alembic commands ###
